### ISSUE TITLE
epic: integrate EAS and Registries

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#20]
## Integrations

The objective of this epic is to integrate the EAS Resolver contract with the Registry contracts. The grants have sensitive data that needs validation before emitting the attestation, the job of the Resolver is to unify all contracts and before we can alter the state of the blockchain we need to validate them.

### Grant Registry
The sensitive data we have on the grant review process is:
- The grantee's address
- The status
- The startDate
This means that:
- If the `grantee` (Grant Interface) address is different than the `attester` (EAS Interface) we need to revert the transaction. 
- If the status is Completed, Cancelled or Rejected, the grantee can only review ONE last time, then he can't no more.
- If the status is Proposed, he cannot review the grant

### Badge Registry
Now about the badges that the user choose. For that we will be using a schema in the registry using arrays or tuples. "DONT DO LIKE ITS IN THE IMAGE ITS JUST A REFERENCE!"
![Image](https://github.com/user-attachments/assets/73a13339-3b00-4273-899a-66a25ae3615f)

You must figure out how to create attestations with arrays so that we can have two arrays:
- badges[]
- scores[]
Where we will be storing the user choice of badges and scores.
So finally about the business rules of the badges:
- Scores must be between 1 and 5
- Badges must be in bytes32 format and must exist in the Badge Registry which can be verified by calling getBadge and checking if it has a name

## Definition of Done:
**To use the blockchain interactions you can use the trustful contracts of 0xneves because the review didn't allow for a merge yet, or hardhat or directly via arbscan. I think via hardhat is easier.**

- [x] chore: deploy grant registry contract arbitrum
- [x] chore: deploy badge registry contract arbitrum
- [x] chore: import deployed contracts to the Karma Resolver repo
- [x] chore: create schemas for the EAS registry using the bytes32 array with badges and scores
- [x] chore: register on-chain the badges that are on the front-end using the badge registry
- [x] chore: register a few grant programs that are available on Karma Gap using the grant register
- [x] feat: create the review validations on the EAS Resolver

## Reference
Badge Registry:
Grant Registry:
https://github.com/0xneves/trustful-contracts

**Comment by RafaDSan** [comment]
Issue closed withing the [Merge](https://github.com/blockful-io/trustful-gap-contracts/commit/7e6f469b668f930114ddde46a2143b49a90a0708)
