### ISSUE TITLE
epic: integration with the backend

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#25]
We are integrating the blockchain back-end into the front-end.
Fixing all possible glitches and providing a seamless experience for the user.

Definition of Done:
- [x] [Integration with the backend](https://github.com/blockful-io/gap-app-v2/pull/9)
- [x] [More integration with backend](https://github.com/blockful-io/gap-app-v2/pull/10)
- [x] [fix: minor bugs and front-end glitches](https://github.com/blockful-io/gap-app-v2/pull/11)
- [x] [fix: wrong state reset when navigating through grants](https://github.com/blockful-io/gap-app-v2/pull/12)
- [x] [feat: merge grant-review to main plus fixes](https://github.com/blockful-io/gap-app-v2/pull/14) 
- [x] [update: card-new-review doc & code improvement](https://github.com/blockful-io/gap-app-v2/pull/13)

We will not fix the CORS related problem, the website uses a lot of blockchain data, so we assume Karma Gap have their own RPC that will support such requests (the main version of gap is using public RPCs)
