### ISSUE TITLE
epic: internal audit

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#26]
I conducted an internal audit to find bugs and misleading documentation. As well as synching with the other repositories.

- [x] [refactor: internal revision](https://github.com/blockful-io/trustful-gap-contracts/pull/23)
- [x] [refactor: second revision eas resolver](https://github.com/blockful-io/trustful-gap-contracts/pull/24) 
- [x] [refactor: internal revision on Trustful](https://github.com/blockful-io/trustful-contracts/pull/8)
